name: Create FINOS Legend release branch

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'The release to create a branch for (yyyy-mm-dd)'
        type: string
        required: true

jobs:
  create-branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "edge"
          fetch-depth: 0

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release-${{ github.event.inputs.release }}"
